DefaultContentLanguage = "es"
baseURL = "/"
disableLanguages = ["en"]
disqusShortname = ""
paginate = "6"
summaryLength = "10"
theme = "biztrox-hugo"
title = "NZEB Ingenería"
[Languages.en]
contentDir = "content/en"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2
[Languages.en.params.footer]
content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim."
copyright = "Copyright &copy; 2019 a hugo theme by [themefisher.com](https://themefisher.com)"
subscribe = "Subscribe Us"
subscribe_content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."
[Languages.es]
contentDir = "content/es"
home = "Home"
languageCode = "es-es"
languageName = "Es"
weight = 1
[Languages.es.params.footer]
content = ""
copyright = "Copyright &copy; 2020 by NZEB Ingeniería"
subscribe = "Suscríbete"
subscribe_content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."
[[menu.footer]]
URL = "#"
name = "Terms & Conditions"
weight = 4
[[menu.footer]]
URL = "#"
name = "Privacy Policy"
weight = 3
[[menu.footer]]
URL = "#"
name = "Sitemap"
weight = 2
[[menu.footer]]
URL = "#"
name = "Legal"
weight = 1
[[menu.main]]
URL = "project"
name = "Proyectos"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contacto"
weight = 6
[[menu.main]]
URL = "team"
name = "Equipo"
weight = 5
[[menu.main]]
URL = "service"
name = "Servicios"
weight = 2
[[menu.main]]
URL = "about"
name = "Acerca de"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[params]
author = "themefisher"
contact_form_action = "#"
description = "NZEB Ingeniería"
google_analitycs_id = "Your ID"
logo = "images/logo-nzeb.png"
logo_white = "images/logo-nzeb-footer.png"
mail = "info@nzebingenieria.es"
mailchimp_form_action = ""
mailchimp_form_name = ""
mobile = "+34 687 49 26 99"
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "41.650120"
map_longitude = "-0.883358"
map_marker = "/images/LOGOTANGRAM.jpg"
[params.nav_button]
enable = false
link = "contact"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate/animate.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
URL = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[[params.clients_logo_slider]]
link = "https://www.bhaus.es/"
logo = "/images/LOGOB HAUS.jpg"
[[params.clients_logo_slider]]
link = "http://www.cabarquitectura.es/"
logo = "/images/LOGOCAB.jpg"
[[params.clients_logo_slider]]
link = "http://www.erarquitectos.com/es"
logo = "/images/LOGOER.jpg"
[[params.clients_logo_slider]]
link = "http://ihp-group.com/"
logo = "/images/LOGOIHP.jpg"
[[params.clients_logo_slider]]
link = "https://gingolfin.wixsite.com/pac17arquitectura"
logo = "/images/PAC17.jpg"
[[params.clients_logo_slider]]
link = "https://qsarquitectos.com/"
logo = "/images/LOGOQS.jpg"
[[params.clients_logo_slider]]
link = "https://www.tangramarquitectura.es/"
logo = "/images/LOGOTANGRAM.jpg"
[[params.clients_logo_slider]]
link = "https://viraje.es/"
logo = "/images/LOGOVIRAJE.jpg"
[[params.contacts]]
icon = "ti-mobile"
[[params.contacts.contact]]
contact_item = "+88 0123 456 789"
[[params.contacts.contact]]
contact_item = "+88 987 654 3210"
[[params.contacts]]
icon = "ti-email"
[[params.contacts.contact]]
contact_item = "info@biztrox.com"
[[params.contacts.contact]]
contact_item = "biztrox@email.com"
[[params.contacts]]
icon = "ti-map-alt"
[[params.contacts.contact]]
contact_item = "24/B Garden Street. <br> Northambia, Weals, UK"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/cjgarciaballano/"
