DefaultContentLanguage = "es"
baseURL = "/"
disableLanguages = ["en"]
disqusShortname = ""
paginate = "6"
summaryLength = "10"
theme = "biztrox-hugo"
title = "NZEB Ingenería"
[Languages.en]
contentDir = "content/en"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2
[Languages.en.params.footer]
content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim."
copyright = "Copyright &copy; 2019 a hugo theme by [themefisher.com](https://themefisher.com)"
subscribe = "Subscribe Us"
subscribe_content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."
[Languages.es]
contentDir = "content/es"
home = "Home"
languageCode = "es-es"
languageName = "Es"
weight = 1
[Languages.es.params.footer]
content = ""
copyright = "Copyright &copy; 2020 by NZEB Ingeniería"
subscribe = "Suscríbete"
subscribe_content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."
[[menu.footer]]
URL = "#"
name = "Terms & Conditions"
weight = 4
[[menu.footer]]
URL = "#"
name = "Privacy Policy"
weight = 3
[[menu.footer]]
URL = "#"
name = "Sitemap"
weight = 2
[[menu.footer]]
URL = "#"
name = "Legal"
weight = 1
[params]
author = "themefisher"
contact_form_action = "#"
description = "NZEB Ingeniería"
google_analitycs_id = "Your ID"
logo = "images/logo-nzeb.png"
logo_white = "images/logo-nzeb-footer.png"
mail = "info@nzebingenieria.es"
mailchimp_form_action = ""
mailchimp_form_name = ""
mobile = "+34 687 49 26 99"
[params.gmap]
enable = true
gmap_api = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d745.3152749214223!2d-0.8837821528587955!3d41.65010037895135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd5914e8e1f4d74b%3A0x2baa075e3cb53945!2zNDHCsDM5JzAwLjQiTiAwwrA1Mic1OS45Ilc!5e0!3m2!1ses!2ses!4v1589478988088!5m2!1ses!2ses"
map_latitude = "45.3152749214223"
map_longitude = "-0.8837821528587955"
map_marker = "/images/logo-nzeb-1.png"
[params.nav_button]
enable = false
link = "contact"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate/animate.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
URL = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[[params.clients_logo_slider]]
link = "https://www.bhaus.es/"
logo = "/images/BHAUS-1.jpg"
[[params.clients_logo_slider]]
link = "http://www.cabarquitectura.es/"
logo = "/images/CAB-1.jpg"
[[params.clients_logo_slider]]
link = "https://equiposinvernales.es/web/"
logo = "/images/EQUIN.jpg"
[[params.clients_logo_slider]]
link = "http://www.erarquitectos.com/es"
logo = "/images/ER-1.jpg"
[[params.clients_logo_slider]]
link = "http://ihp-group.com/"
logo = "/images/IHP-1.jpg"
[[params.clients_logo_slider]]
link = "https://gingolfin.wixsite.com/pac17arquitectura"
logo = "/images/PAC17-2.jpg"
[[params.clients_logo_slider]]
link = "https://qsarquitectos.com/"
logo = "/images/QS-1.jpg"
[[params.clients_logo_slider]]
link = "https://www.tangramarquitectura.es/"
logo = "/images/Tangram-1.jpg"
[[params.clients_logo_slider]]
link = "https://viraje.es/"
logo = "/images/Viraje.jpg"
[[params.contacts]]
icon = "ti-mobile"
[[params.contacts.contact]]
contact_item = "+34 876 16 47 57"
[[params.contacts.contact]]
contact_item = "+34 687 49 26 99"
[[params.contacts]]
icon = "ti-email"
[[params.contacts.contact]]
contact_item = "info@nzebingenieria.es"
[[params.contacts.contact]]
contact_item = "cjgarcia@nzebingenieria.es"
[[params.contacts]]
icon = "ti-map-alt"
[[params.contacts.contact]]
contact_item = "Paseo de la Independencia 24-26</p>50004 Zaragoza (España)"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/cjgarciaballano/"
